### ISSUE TITLE
Error when running the application - Error: write after end

### ISSUE THREAD

**Issue by dongido001** [nokenwa/twilio-media-stream-live-transcription-node#1]
I get this error when I try to run the application

```
Error: write after end
    at writeAfterEnd (/Users/dongido/projects/twilio-media-stream-live-transcription-node/node_modules/readable-stream/lib/_stream_writable.js:257:12)
    at Pumpify.Writable.write (/Users/dongido/projects/twilio-media-stream-live-transcription-node/node_modules/readable-stream/lib/_stream_writable.js:301:21)
```

**Comment by nokenwa** [comment]
I'm trying to recreate this error can you give me a bit more info about what happens before this error.

**Comment by dongido001** [comment]
Thanks, @nokenwa I figured it out, it was because my google credential does not have the right permission
