### ISSUE TITLE
Getting Error: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by yashShelatkar** [nokenwa/twilio-media-stream-live-transcription-node#4]
So, I tried doing same as the article suggests yet I have got this wired error, I have double checked everything, can you have a look at this?

Error Log:

Error: Cannot call write after a stream was destroyed
    at doWrite (/Users/melatidehaas/Desktop/twilio-streams/node_modules/pumpify/node_modules/readable-stream/lib/_stream_writable.js:405:38)
    at writeOrBuffer (/Users/melatidehaas/Desktop/twilio-streams/node_modules/pumpify/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at Pumpify.Writable.write (/Users/melatidehaas/Desktop/twilio-streams/node_modules/pumpify/node_modules/readable-stream/lib/_stream_writable.js:303:11)
    at WebSocket.incoming (/Users/melatidehaas/Desktop/twilio-streams/index.js:58:25)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/Users/melatidehaas/Desktop/twilio-streams/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/Users/melatidehaas/Desktop/twilio-streams/node_modules/ws/lib/receiver.js:423:14)
    at Receiver.getData (/Users/melatidehaas/Desktop/twilio-streams/node_modules/ws/lib/receiver.js:353:17)
    at Receiver.startLoop (/Users/melatidehaas/Desktop/twilio-streams/node_modules/ws/lib/receiver.js:139:22)

**Comment by nokenwa** [comment]
Heya,
Sorry about the late reply, I've been away at events and only just catching back up.

**Comment by yashShelatkar** [comment]
No Problem, I am still stuck with this issue, is there any particular reason usually for this error?

**Comment by nokenwa** [comment]
Just checking that you have included your .env file with your Google Credentials?

**Comment by yashShelatkar** [comment]
Yup, I have.

**Comment by nokenwa** [comment]
Does this happen from the start or was the transcription working then this message come up?

**Comment by yashShelatkar** [comment]
Apparently I just checked it again the error is gone, although Live Transcribe doesn't show yet.

**Comment by nokenwa** [comment]
Hmmm interesting, any logs?

**Comment by yashShelatkar** [comment]
I updated the ngrok package and it did helped, the issue is solved thanks for the help. 

![Screen Shot 2019-10-23 at 1 55 20 am](https://user-images.githubusercontent.com/25059239/67299700-bc70e600-f538-11e9-9b68-c1c55f46345f.png)

**Comment by kylemcdonald** [comment]
I had this problem, and it turned out I was using a relative path to the JSON credentials with the incorrect root. Switching to an absolute path, or to the correct relative path, both fixed the problem.
